### ISSUE TITLE
Plugin xml

### ISSUE THREAD

**Issue by leecrossley** [DickvdBrink/cordova-indexeddb#1]
`cordova plugin add https://github.com/DickvdBrink/cordova-indexeddb.git` will not work without a valid plugin.xml file

**Comment by DickvdBrink** [comment]
I know, not finished yet :)
Will work on it soon!
edit: Thanks for creating an issue for it anyways :)

**Comment by DickvdBrink** [comment]
Added plugin.xml file so it installs correctly.
